books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id": 2,
        "title": "深入理解计算机系统",
        "author": "Randal E. Bryant",
        "publisher": "机械工业出版社",
        "published_date": "2016-11-01",
        "page_count": 737,
        "language": "Chinese",
    },
    {
        "id": 3,
        "title": "算法导论",
        "author": "Thomas H. Cormen",
        "publisher": "MIT Press",
        "published_date": "2009-07-24",
        "page_count": 1312,
        "language": "English",
    },
    {
        "id": 4,
        "title": "代码大全",
        "author": "Steve McConnell",
        "publisher": "电子工业出版社",
        "published_date": "2006-03-01",
        "page_count": 914,
        "language": "Chinese",
    },
    {
        "id": 5,
        "title": "Design Patterns",
        "author": "Erich Gamma",
        "publisher": "Addison-Wesley Professional",
        "published_date": "1994-10-21",
        "page_count": 395,
        "language": "English",
    },
    {
        "id": 6,
        "title": "重构：改善既有代码的设计",
        "author": "Martin Fowler",
        "publisher": "人民邮电出版社",
        "published_date": "2019-04-01",
        "page_count": 342,
        "language": "Chinese",
    },
    {
        "id": 7,
        "title": "计算机网络：自顶向下方法",
        "author": "James F. Kurose",
        "publisher": "机械工业出版社",
        "published_date": "2018-06-01",
        "page_count": 488,
        "language": "Chinese",
    },
    {
        "id": 8,
        "title": "Effective Java",
        "author": "Joshua Bloch",
        "publisher": "Addison-Wesley Professional",
        "published_date": "2017-10-19",
        "page_count": 286,
        "language": "English",
    },
    {
        "id": 9,
        "title": "操作系统概念",
        "author": "Abraham Silberschatz",
        "publisher": "John Wiley & Sons",
        "published_date": "2018-11-12",
        "page_count": 976,
        "language": "English",
    },
    {
        "id": 10,
        "title": "流畅的Python",
        "author": "Luciano Ramalho",
        "publisher": "人民邮电出版社",
        "published_date": "2017-05-01",
        "page_count": 720,
        "language": "Chinese",
    },
]
